# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# C:\ci\containers\00001nv17gs\tmp\build\80754af9\rsync-recipes\six-1.14.0-python_3.7-on-winbuilder, last modified Mon Jan 27 18:26:22 2020
# ------------------------------------------------

package:
    name: six
    version: 1.14.0
source:
    sha256: 236bdbdce46e6e6a3d61a337c0f8b763ca1e8717c03b369e87a7ec7ce1319c0a
    url: https://pypi.io/packages/source/s/six/six-1.14.0.tar.gz
build:
    number: '0'
    script: C:\ci\six_1580149919647\_h_env\python.exe -m pip install --no-deps --ignore-installed
        .
    string: py37_0
requirements:
    host:
        - ca-certificates 2019.11.27 0
        - certifi 2019.11.28 py37_0
        - openssl 1.1.1d he774522_3
        - pip 19.3.1 py37_0
        - python 3.7.6 h60c2a47_2
        - setuptools 44.0.0 py37_0
        - sqlite 3.30.1 he774522_0
        - vc 14.1 h0510ff6_4
        - vs2015_runtime 14.16.27012 hf0eaf9b_1
        - wheel 0.33.6 py37_0
        - wincertstore 0.2 py37_0
    run:
        - python >=3.7,<3.8.0a0
test:
    imports:
        - six
about:
    description: 'Six provides simple utilities for wrapping over differences between

        Python 2 and Python 3. It is intended to support codebases that work on

        both Python 2 and 3 without modification. six consists of only one Python

        file, so it is painless to copy into a project.

        '
    dev_url: https://github.com/benjaminp/six
    doc_url: https://six.readthedocs.io/
    home: https://six.readthedocs.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: Python 2 and 3 compatibility utilities
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - jakirkham
        - msarahan
        - ocefpaf
